# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.7'

services:

  jstor-transformer:
    container_name: 'jstor-transformer'
    build:
      context: './'
      dockerfile: './DockerfileLocal'
    volumes:
      - './:/home/jstorforumadm'
      - '/tmp:/tmp'
      - './harvestjobs.json:/home/jstorforumadm/harvestjobs.json'
    env_file:
      - '.env'
    environment:

      QUEUE_NAME: proto_transform
      NEXT_QUEUE_NAME: proto_publisher

    ports:
      # Worker API
      - '25001:8081'
    networks:
      - jstorforum-net

# Create a custom docker network if it does not exist already
networks:
  jstorforum-net:
    name: jstorforum-net
